using Sparks.Api.Common.Errors;

namespace Sparks.Api.Storage;

/// <summary>Checks images before they're stored: their size, and what their bytes say they are.</summary>
public sealed class ImageUploadService(IFileStorage storage)
{
    public const long MaxAvatarBytes = 2 * 1024 * 1024;
    public const long MaxImageBytes = 5 * 1024 * 1024;

    /// <summary>
    /// The request size the upload endpoints accept: the largest image plus
    /// room for the multipart envelope. Bigger requests are cut off before
    /// they're read.
    /// </summary>
    public const long MaxRequestBytes = MaxImageBytes + (64 * 1024);

    /// <summary>Stores an uploaded image for its owner and returns its key.</summary>
    public async Task<string> SaveAsync(IFormFile file, string folder, long ownerId, long maxBytes, CancellationToken ct)
    {
        if (file.Length == 0)
        {
            throw ApiException.BadRequest("EMPTY_FILE", "The file is empty.");
        }

        if (file.Length > maxBytes)
        {
            throw ApiException.BadRequest("IMAGE_TOO_LARGE", $"Images can be up to {maxBytes / (1024 * 1024)} MB.");
        }

        await using var content = file.OpenReadStream();
        return await SaveAsync(content, folder, ownerId, ct);
    }

    /// <summary>
    /// Stores an image from a seekable stream (an upload or generated bytes)
    /// and returns its key. The name and declared type are ignored; the
    /// first bytes decide the format, so nothing else can pass as an image.
    /// </summary>
    public async Task<string> SaveAsync(Stream content, string folder, long ownerId, CancellationToken ct)
    {
        var header = new byte[ImageFormats.HeaderLength];
        var read = await content.ReadAtLeastAsync(header, header.Length, throwOnEndOfStream: false, ct);
        var format = ImageFormats.Detect(header.AsSpan(0, read))
            ?? throw ApiException.BadRequest("UNSUPPORTED_IMAGE", "Images must be PNG, JPEG, GIF or WebP.");

        content.Position = 0;
        var key = StorageKeys.New(folder, ownerId, format);
        await storage.SaveAsync(key, content, ct);
        return key;
    }
}
